---
apiVersion: v1
kind: Service
metadata:
  name: aws9-service
  namespace: aw9c
spec:
  selector:
    color: black
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9-deploy-blog
  namespace: aw9c
spec:
  replicas: 3
  selector:
    matchLabels:
      color: black  # 나는 이러한 key: value 를 갖는 Pod 를 3개 유지할게!!! (controller가 담당)
  template:       # 실제적인 Pod 의 구성 정보
    metadata:
      labels:
        color: black
    spec:
      containers:
        - name: aws9c-blog
          image: brian24/aws9:blog
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "250m"
---
apiVersion: autoscaling/v1      # autoscaling part
kind: HorizontalPodAutoscaler
metadata:
  name: aws9-hpa
  namespace: aws9c
spec:
  maxReplicas: 15
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws9-deploy-black
  targetCPUUtilizationPercentage: 60


