apiVersion: keda.sh/v2alpha1
kind: ScaledObject
metadata:
  name: shop-scaledobject
  namespace: aws9c
spec:
  scaleTargetRef:
    name: aws9-deploy-shop
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Seoul
      start: "0 9 * * *"       # 오전 9시
      end: "0 18 * * *"        # 오후 6시
      desiredReplicas: "3"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shop-hpa
  namespace: aws9c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
